import glob
from PIL import Image


def print_debug_log(string):
    """Print debug string"""
    print(string)


class EvaluationException(Exception):
    """Exception that needs to be handled by the user. Usually indicative of bad environment."""

    pass


def abstract_generator(str_gen, wd):
    """Strings generated by str_gen are used to glob for files in wd, which are sequentially returned."""
    while True:
        next_str_match = next(str_gen)
        matched_files = glob.glob(wd + next_str_match)
        if len(matched_files) == 1:
            yield matched_files[0]
        else:
            if len(matched_files) > 1:
                raise EvaluationException(
                    f"[{wd}] {len(matched_files)} files found matching glob"
                    "{next_str_match}: {', '.join(matched_files)} "
                )
            else:
                print_debug_log(f"[{wd}] search terminated at {next_str_match}")
                return


def increasing_gen():
    """Natural number generator."""
    i = 1
    while True:
        yield i
        i += 1


def number_glob_gen(re, pos):
    """Generates glob (with number inserted at pos)."""
    return (re[:pos] + str(i) + re[pos:] for i in increasing_gen())


def order_list(re, pos, wd):
    """Get ordered list with th"""
    return abstract_generator(number_glob_gen(re, pos), wd)


def main():
    try:
        book_path = "/Volumes/KOBOeReader/Library/GPUBundles/x64compatible/kube/"
        chap_name = "Volume. 1 Chapter. 1"
        books = list(order_list("?-*.jpg", 1, chap_name + "/"))
        books = [Image.open(book_path + name) for name in books]
        books[0].save(
            book_path + chap_name + ".pdf",
            "PDF",
            resolution=100.0,
            save_all=True,
            append_images=books[1:],
        )
        pass
    except EvaluationException as e:
        print("Evaluation Exception. Please resolve before rerunning.")
        print(e)


if __name__ == "__main__":
    main()
